=== macomfan/cei/schema/ceisdk-0.0.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://github.com/macomfan/cei"
           xmlns="https://github.com/macomfan/cei"
           elementFormDefault="qualified"
           version="0.0.1">
    <xs:element name="sdk" type="xSDK"/>

    <xs:complexType name="xSDK">
        <xs:all>
            <xs:element name="definition" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="document"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="models" minOccurs="0">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="model" type="xModel"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="procedures" minOccurs="0">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="function" type="xFunction" maxOccurs="unbounded"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="clients" minOccurs="0">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="restful" type="xRestful"/>
                        <xs:element name="websocket" type="xWebSocket"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>


    <xs:complexType name="xSDKDef">
        <xs:attribute name="document"/>
    </xs:complexType>

    <xs:complexType name="xModel">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="string" type="xType"/>
            <xs:element name="int" type="xType"/>
            <xs:element name="decimal" type="xType"/>
            <xs:element name="boolean" type="xType"/>
            <xs:element name="object" type="xObject"/>
            <xs:element name="object_array" type="xObjectArray"/>
            <xs:element name="string_array" type="xType"/>
            <xs:element name="int_array" type="xType"/>
            <xs:element name="decimal_array" type="xType"/>
            <xs:element name="boolean_array" type="xType"/>
        </xs:choice>
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>

    <xs:complexType name="xRestful">
        <xs:all>
            <xs:element name="connection" type="xConnection" minOccurs="0"/>
            <xs:element name="interfaces" minOccurs="0">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="interface">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="inputs" minOccurs="0" type="xInputs"/>
                                    <xs:element name="request" type="xRequest"/>
                                    <xs:element name="response" type="xResponse"/>
                                </xs:sequence>
                                <xs:attribute name="name" use="required" type="nameType"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>

    <xs:complexType name="xWebSocket">
        <xs:all>
            <xs:element name="connection" type="xWSConnection" minOccurs="0"/>
            <xs:element name="actions" minOccurs="0">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="action">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="trigger" type="xTrigger"/>
                                    <xs:element name="send" type="xSend"/>
                                </xs:sequence>
                                <xs:attribute name="name" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="interfaces" minOccurs="0">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="interface">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="inputs" minOccurs="0" type="xInputs"/>
                                    <xs:element name="send" minOccurs="0" type="xSend"/>
                                    <xs:element name="callback" type="xCallback" maxOccurs="unbounded"/>
                                </xs:sequence>
                                <xs:attribute name="name" use="required" type="nameType"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>

    <xs:complexType name="xType">
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>
    <xs:complexType name="xObject">
        <xs:attribute name="name" use="required" type="nameType"/>
        <xs:attribute name="model" use="required" type="nameType"/>
    </xs:complexType>
    <xs:complexType name="xObjectArray">
        <xs:attribute name="name" use="required" type="nameType"/>
        <xs:attribute name="model" use="required" type="nameType"/>
    </xs:complexType>

    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z]+[A-Za-z0-9_]*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="variableType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\{[A-Za-z]+[A-Za-z0-9_]*\}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="xRequest">
        <xs:sequence>
            <xs:element name="pre_processor" type="xProcedure" minOccurs="0"/>
            <xs:element name="query_strings" type="xQueryStrings" minOccurs="0"/>
            <xs:element name="post_body" minOccurs="0" type="xPostBody"/>
            <xs:element name="authentication" minOccurs="0" type="xAuthentication"/>
        </xs:sequence>
        <xs:attribute name="method" use="required" type="httpMethodType"/>
        <xs:attribute name="target" use="required" type="xs:string"/>
    </xs:complexType>
    <xs:simpleType name="httpMethodType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="get"/>
            <xs:enumeration value="post"/>
            <xs:enumeration value="delete"/>
            <xs:enumeration value="put"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="xResponse">
        <xs:complexContent>
            <xs:extension base="xProcedure">
                <xs:attribute name="name" type="nameType"/>
                <xs:attribute name="result" type="variableType"/>
                <xs:attribute name="type" type="ResponseType"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="xInputs">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="string" type="xType"/>
            <xs:element name="int" type="xType"/>
            <xs:element name="decimal" type="xType"/>
            <xs:element name="boolean" type="xType"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="xQueryStrings">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="query" type="xQuery"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="xQuery">
        <xs:attribute name="key" use="required" type="nameType"/>
        <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="xPostBody">
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>


    <!--======== For JSON Start =======-->
    <xs:complexType name="xJsonType">
        <xs:attribute name="key" type="xs:string"/>
        <xs:attribute name="copy" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="xJsonWithSubItems">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="json_value" type="xJsonType"/>
            <xs:element name="json_string" type="xJsonType"/>
            <xs:element name="json_boolean" type="xJsonType"/>
            <xs:element name="json_decimal" type="xJsonType"/>
            <xs:element name="json_object_for_each" type="xJsonTypeWithModel"/>
            <xs:element name="json_object" type="xJsonTypeWithModel"/>
            <xs:element name="json_string_array" type="xJsonType"/>
            <xs:element name="json_int_array" type="xJsonType"/>
            <xs:element name="json_boolean_array" type="xJsonType"/>
            <xs:element name="json_decimal_array" type="xJsonType"/>
            <xs:element name="json_checker_equal" type="xJsonCheckerItem"/>
            <xs:element name="json_checker_not_equal" type="xJsonCheckerItem"/>
        </xs:choice>
    </xs:complexType>


    <xs:complexType name="xJsonParser">
        <xs:complexContent>
            <xs:restriction base="xJsonWithSubItems">
                <xs:choice minOccurs="0">
                    <xs:element name="json_checker" type="xJsonWithSubItems"/>
                </xs:choice>
                <xs:attribute name="model" type="nameType" use="required"/>
                <xs:attribute name="name" type="nameType"/>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="xJsonTypeWithModel">
        <xs:complexContent>
            <xs:extension base="xJsonWithSubItems">
                <xs:attribute name="key" type="xs:string"/>
                <xs:attribute name="copy" type="xs:string"/>
                <xs:attribute name="value" type="xs:string"/>
                <xs:attribute name="model" type="nameType"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="xJsonBuilder">
        <xs:complexContent>
            <xs:extension base="xJsonWithSubItems">
                <xs:attribute name="name" type="nameType"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="xJsonCheckerItem">
        <xs:attribute name="key"/>
        <xs:attribute name="value"/>
    </xs:complexType>

    <xs:complexType name="xJsonBuilderItem">
        <xs:attribute name="key" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
        <xs:attribute name="copy" type="xs:string"/>
    </xs:complexType>

    <!--======== For JSON End =======-->

    <!--======== For Function Start =========-->
    <xs:complexType name="xProcedure">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="json_parser" type="xJsonParser"/>
            <xs:element name="json_builder" type="xJsonBuilder"/>
            <xs:element name="get_now" type="xGetNow"/>
            <xs:element name="string_builder" type="xStringBuilder"/>
            <xs:element name="hmacsha256" type="xHmacsha256"/>
            <xs:element name="base64" type="xBase64"/>
            <xs:element name="get_now" type="xGetNow"/>
            <xs:element name="url_escape" type="xURLEscape"/>
            <xs:element name="string_builder" type="xStringBuilder"/>
            <xs:element name="add_query_string" type="xAddQueryString"/>
            <xs:element name="combine_query_string" type="xCombineQueryString"/>
            <xs:element name="get_request_info" type="xGetRequestInfo"/>
            <xs:element name="invoke" type="xInvoke"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="xExtendInput">
        <xs:complexContent>
            <xs:extension base="xInputs">
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="restful_request" type="xType"/>
                    <xs:element name="restful_options" type="xType"/>
                    <xs:element name="restful_response" type="xType"/>
                    <xs:element name="websocket_message" type="xType"/>
                    <xs:element name="websocket_request" type="xType"/>
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="xFunction">
        <xs:sequence>
            <xs:element name="inputs" minOccurs="0" type="xExtendInput"/>
            <xs:element name="implementation" type="xProcedure"/>
        </xs:sequence>
        <xs:attribute name="name" type="nameType" use="required"/>
        <xs:attribute name="return" type="variableType"/>
    </xs:complexType>
    <!--======== For Function End   =========-->

    <!-- Data processor -->
    <xs:complexType name="xGetNow">
        <xs:attribute name="name" type="nameType"/>
        <xs:attribute name="format" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="xAddQueryString">
        <xs:attribute name="input" type="variableType" use="required"/>
        <xs:attribute name="key" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="xCombineQueryString">
        <xs:attribute name="input" type="variableType" use="required"/>
        <xs:attribute name="name" type="nameType"/>
        <xs:attribute name="sort"/>
        <xs:attribute name="separator"/>
    </xs:complexType>
    <xs:complexType name="xGetRequestInfo">
        <xs:attribute name="input" type="variableType" use="required"/>
        <xs:attribute name="name" type="nameType"/>
        <xs:attribute name="info"/>
        <xs:attribute name="convert"/>
    </xs:complexType>
    <xs:complexType name="xHmacsha256">
        <xs:attribute name="name" type="nameType"/>
        <xs:attribute name="input"/>
        <xs:attribute name="key"/>
    </xs:complexType>
    <xs:complexType name="xBase64">
        <xs:attribute name="name" type="nameType"/>
        <xs:attribute name="input"/>
    </xs:complexType>

    <xs:complexType name="xConnection">
        <xs:attribute name="url" type="xs:string" use="required"/>
        <xs:attribute name="timeout_s" type="xs:integer"/>
    </xs:complexType>


    <xs:complexType name="xCallback">
        <xs:sequence>
            <xs:element name="trigger" type="xTrigger"/>
            <xs:element name="response" type="xResponse"/>
        </xs:sequence>
        <xs:attribute name="name" use="required" type="nameType"/>
        <xs:attribute name="persistent" use="required" type="xs:boolean"/>
    </xs:complexType>
    <xs:simpleType name="WebSocketCallbackType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="disposable"/>
            <xs:enumeration value="persistent"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="xTrigger">
        <xs:choice>
            <xs:element name="json_checker" type="xJsonWithSubItems"/>
        </xs:choice>
        <xs:attribute name="timeout_s" type="xs:integer"/>
        <xs:attribute name="interval_s" type="xs:integer"/>
    </xs:complexType>
    <xs:complexType name="xSend">
        <xs:complexContent>
            <xs:extension base="xProcedure">
                <xs:attribute name="value" type="xs:string" use="required"/>
                <xs:attribute name="type" type="WebSocketSendType"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="WebSocketSendType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="string"/>
            <xs:enumeration value="binary"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ResponseType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="string"/>
            <xs:enumeration value="binary"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="xStringBuilder">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="add_string_item" type="xAddStringItem"/>
            <xs:element name="combine_string_items" type="xCombineStringItems"/>
        </xs:choice>
        <xs:attribute name="name" type="nameType"/>
    </xs:complexType>
    <xs:complexType name="xAddStringItem">
        <xs:attribute name="input"/>
    </xs:complexType>
    <xs:complexType name="xCombineStringItems">
        <xs:attribute name="separator"/>
    </xs:complexType>
    <xs:complexType name="xWSConnection">
        <xs:sequence>
            <xs:element name="inputs" type="xInputs" minOccurs="0"/>
            <xs:element name="url" type="xWSUrl"/>
            <xs:element name="on_connect" minOccurs="0" type="xWSOnConnect"/>
        </xs:sequence>
        <xs:attribute name="timeout_s" type="xs:integer"/>
    </xs:complexType>
    <xs:complexType name="xWSUrl">
        <xs:choice minOccurs="0">
            <xs:element name="attribute" type="xProcedure"/>
        </xs:choice>
        <xs:attribute name="target"/>
    </xs:complexType>
    <xs:complexType name="xWSOnConnect">
        <xs:choice minOccurs="0">
            <xs:element name="send" type="xSend"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="xURLEscape">
        <xs:attribute name="name" type="nameType"/>
        <xs:attribute name="input" type="variableType"/>
    </xs:complexType>

    <xs:complexType name="xAuthentication">
        <xs:attribute name="name" type="nameType" use="required"/>
        <xs:attribute name="arguments" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="xInvoke">
        <xs:attribute name="function" type="nameType" use="required"/>
        <xs:attribute name="return" type="variableType"/>
        <xs:attribute name="arguments" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== macomfan/cei/exchanges/binance/models/Symbol.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="https://github.com/macomfan/cei https://macomfan.github.io/cei/schema/ceisdk-0.0.1.xsd"
     xmlns="https://github.com/macomfan/cei"
     name="binance">
	<models>
		<model name="Symbol">
			<string name="symbol"/>
			<string name="status"/>
			<string name="baseAsset"/>
			<int name="baseAssetPrecision"/>
			<string name="quoteAsset"/>
			<int name="quotePrecision"/>
			<string_array name="orderTypes"/>
			<boolean name="icebergAllowed"/>
			<boolean name="ocoAllowed"/>
		</model>
	</models>

</sdk>

=== macomfan/cei/exchanges/huobipro/models/LastTrade.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="https://github.com/macomfan/cei https://macomfan.github.io/cei/schema/ceisdk-0.0.1.xsd"
     xmlns="https://github.com/macomfan/cei"
     name="huobipro">
    <models>
    <model name="LastTrade">
        <string name="status"/>
        <string name="ch"/>
        <int name="ts"/>
        <int name="tsInTick"/>
        <int name="idInTick"/>
        <object_array name="data" model="Trade"/>
    </model>
    </models>
</sdk>

=== macomfan/cei/exchanges/binance/models.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="https://github.com/macomfan/cei https://macomfan.github.io/cei/schema/ceisdk-0.0.1.xsd"
     xmlns="https://github.com/macomfan/cei"
     name="binance">
    <models>
        <model name="CandlestickData">
            <int name="openTime"/>
            <decimal name="open"/>
            <decimal name="high"/>
            <decimal name="low"/>
            <decimal name="close"/>
            <decimal name="volume"/>
            <int name="closeTime"/>
            <decimal name="quoteAssetVolume"/>
            <int name="numberOfTrades"/>
            <decimal name="takerBuyBaseAssetVolume"/>
            <decimal name="takerBuyQuoteAssetVolume"/>
        </model>

        <model name="CandlestickDataList">
            <object_array name="data" model="CandlestickData"/>
        </model>

        <model name="Depth">
            <int name="lastUpdateId"/>
            <object_array name="bids" model="DepthEntity"/>
            <object_array name="asks" model="DepthEntity"/>
        </model>

        <model name="DepthEntity">
            <decimal name="price"/>
            <decimal name="qty"/>
        </model>

        <model name="ExchangeInfo">
            <string name="timezone"/>
            <int name="serverTime"/>
            <object_array name="rateLimits" model="RateLimits"/>
            <object_array name="symbols" model="Symbol"/>
        </model>

        <model name="RateLimits">
            <string name="rateLimitType"/>
            <string name="interval"/>
            <int name="intervalNum"/>
            <int name="limit"/>
        </model>

        <model name="Timestamp">
            <int name="serverTime"/>
        </model>

        <model name="CandlestickStream">
            <string name="symbol"/>
        </model>

        <model name="TradeList">
            <object_array name="data" model="Trade"/>
        </model>

        <model name="Trade">
            <int name="id"/>
            <decimal name="price"/>
            <decimal name="qty"/>
            <decimal name="quoteQty"/>
            <int name="time"/>
            <boolean name="isBuyerMaker"/>
            <boolean name="isBestMatch"/>
        </model>

        <model name="Symbol">
            <string name="symbol"/>
            <string name="status"/>
            <string name="baseAsset"/>
            <int name="baseAssetPrecision"/>
            <string name="quoteAsset"/>
            <int name="quotePrecision"/>
            <string_array name="orderTypes"/>
            <boolean name="icebergAllowed"/>
            <boolean name="ocoAllowed"/>
        </model>

        <model name="AggregateTrade">
            <int name="id"/>
            <decimal name="price"/>
            <decimal name="qty"/>
            <int name="timestamp"/>
            <int name="firstTradeId"/>
            <int name="lastTradeId"/>
            <boolean name="isBuyerMaker"/>
            <boolean name="isBestMatch"/>
        </model>

        <model name="AggregateTradeList">
            <object_array name="data" model="AggregateTrade"/>
        </model>
    </models>
</sdk>

=== macomfan/cei/exchanges/huobipro/models.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="https://github.com/macomfan/cei https://macomfan.github.io/cei/schema/ceisdk-0.0.1.xsd"
     xmlns="https://github.com/macomfan/cei"
     name="huobipro">
    <models>
        <model name="Account">
            <string name="status"/>
            <object_array name="data" model="AccountData"/>
        </model>

        <model name="AccountData">
            <int name="id"/>
            <string name="state"/>
            <string name="type"/>
            <string name="subtype"/>
        </model>

        <model name="Trade">
            <int name="id"/>
            <int name="tradeID"/>
            <decimal name="price"/>
            <decimal name="amount"/>
            <string name="direction"/>
            <int name="ts"/>
        </model>

        <model name="BestQuote">
            <string name="status"/>
            <string name="ch"/>
            <int name="ts"/>
            <decimal name="bestBidPrice"/>
            <decimal name="bestBidAmount"/>
            <decimal name="bestAskPrice"/>
            <decimal name="bestAskAmount"/>
        </model>

        <model name="Candlestick">
            <string name="status"/>
            <object_array name="data" model="CandlestickData"/>
        </model>

        <model name="CandlestickData">
            <int name="id"/>
            <decimal name="amount"/>
            <int name="count"/>
            <decimal name="open"/>
            <decimal name="close"/>
            <decimal name="low"/>
            <decimal name="high"/>
            <decimal name="vol"/>
        </model>

        <model name="Currencies">
            <string name="status"/>
            <string_array name="data"/>
        </model>

        <model name="LastTrade">
            <string name="status"/>
            <string name="ch"/>
            <int name="ts"/>
            <int name="tsInTick"/>
            <int name="idInTick"/>
            <object_array name="data" model="Trade"/>
        </model>

        <model name="Depth">
            <string name="status"/>
            <string name="ch"/>
            <int name="ts"/>
            <object_array name="bids" model="Quote"/>
            <object_array name="asks" model="Quote"/>
        </model>

        <model name="OrderID">
            <string name="status"/>
            <int name="data"/>
        </model>

        <model name="Quote">
            <decimal name="price"/>
            <decimal name="amount"/>
        </model>

        <model name="Symbols">
            <string name="status"/>
            <object_array name="data" model="SymbolsData"/>
        </model>

        <model name="SymbolsData">
            <string name="baseCurrency"/>
            <string name="quoteCurrency"/>
            <int name="pricePrecision"/>
            <int name="amountPrecision"/>
            <string name="symbolPartition"/>
            <string name="symbol"/>
            <string name="state"/>
            <int name="valuePrecision"/>
            <decimal name="minOrderAmt"/>
            <decimal name="maxOrderAmt"/>
            <decimal name="minOrderValue"/>
            <int name="leverageRatio"/>
        </model>

        <model name="Timestamp">
            <int name="timestamp"/>
        </model>
        
        <model name="AggregatedMarketData">
            <int name="id"/>
            <decimal name="amount"/>
            <int name="count"/>
            <decimal name="open"/>
            <decimal name="close"/>
            <decimal name="low"/>
            <decimal name="high"/>
            <decimal name="vol"/>
            <decimal name="bidPrice"/>
            <decimal name="bidSize"/>
            <decimal name="askPrice"/>
            <decimal name="askSize"/>
        </model>

        <model name="OrderUpdate">
            <string name="eventType"/>
            <string name="symbol"/>
            <int name="orderId"/>
            <string name="clientOrderId"/>
            <string name="orderPrice"/>
            <string name="orderSize"/>
            <string name="type"/>
            <string name="orderStatus"/>
            <int name="orderCreateTime"/>
            <string name="tradePrice"/>
            <string name="tradeVolume"/>
            <int name="tradeId"/>
            <int name="tradeTime"/>
            <boolean name="aggressor"/>
            <string name="remainAmt"/>
            <string name="lastActTime"/>
        </model>
    </models>
</sdk>

=== macomfan/cei/exchanges/binance/restful/MarketClient/getTrade.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="https://github.com/macomfan/cei https://macomfan.github.io/cei/schema/ceisdk-0.0.1.xsd"
	 xmlns="https://github.com/macomfan/cei"
	 name="binance">
	<clients>
		<restful name="MarketClient">
			<interfaces>
				<interface name="getTrade">
					<inputs>
						<string name="symbol"/>
						<int name="limit"/>
					</inputs>
					<request method="get" target="/api/v3/trades">
						<query_strings>
							<query key="symbol" value="{symbol}"/>
							<query key="limit" value="{limit}"/>
						</query_strings>
					</request>
					<response>
						<json_parser model="TradeList">
							<json_object_for_each value="{data}" model="Trade">
								<json_value copy="id"/>
								<json_value copy="price"/>
								<json_value copy="qty"/>
								<json_value copy="quoteQty"/>
								<json_value copy="time"/>
								<json_value copy="isBuyerMaker"/>
								<json_value copy="isBestMatch"/>
							</json_object_for_each>
						</json_parser>
					</response>
				</interface>
			</interfaces>
		</restful>
	</clients>

</sdk>
