=== macomfan/cei/schema/ceisdk.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://aaa"
           xmlns="https://aaa"
           elementFormDefault="qualified">
    <xs:element name="sdk" type="xSDK"/>

    <xs:complexType name="xSDK">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="definition" type="xSDKDefinition"/>
            <xs:element name="authentication" type="xSignature" maxOccurs="unbounded"/>
            <xs:element name="model" type="xModel" maxOccurs="unbounded"/>
            <xs:element name="restful" type="xRestful" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>

    <xs:complexType name="xSDKDefinition">
        <xs:attribute name="document"/>
    </xs:complexType>

    <!--    <xs:complexType name="xRestfulDefinition">-->
    <!--        <xs:sequence>-->
    <!--            <xs:element name="name" minOccurs="1" maxOccurs="1"/>-->
    <!--            <xs:element name="url" minOccurs="1" maxOccurs="1"/>-->
    <!--        </xs:sequence>-->
    <!--    </xs:complexType>-->


    <xs:complexType name="xModel">
        <xs:choice>
            <xs:element name="string" type="xType"/>
            <xs:element name="int" type="xType"/>
            <xs:element name="decimal" type="xType"/>
            <xs:element name="boolean" type="xType"/>
            <xs:element name="object" type="xObject"/>
            <xs:element name="object_array" type="xObjectArray"/>
            <xs:element name="string_array" type="xType"/>
            <xs:element name="int_array" type="xType"/>
            <xs:element name="decimal_array" type="xType"/>
            <xs:element name="boolean_array" type="xType"/>
        </xs:choice>
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>

    <xs:complexType name="xRestful">
        <xs:choice>
            <xs:element name="definition"/>
            <xs:element name="interface" type="xInterface" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>

    <xs:complexType name="xType">
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>
    <xs:complexType name="xObject">
        <xs:attribute name="name" use="required" type="nameType"/>
        <xs:attribute name="model" use="required" type="nameType"/>
    </xs:complexType>
    <xs:complexType name="xObjectArray">
        <xs:attribute name="name" use="required" type="nameType"/>
        <xs:attribute name="model" use="required" type="nameType"/>
    </xs:complexType>

    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z][A-Za-z0-9]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="xSignature">
    </xs:complexType>


    <xs:complexType name="xInterface">
        <xs:sequence>
            <xs:element name="inputs" minOccurs="0" type="xInputs"/>
            <xs:element name="request" type="xRequest"/>
            <xs:element name="response" type="xResponse"/>
        </xs:sequence>
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>
    <xs:complexType name="xRequest">
        <xs:sequence>
            <xs:element name="query_strings" type="xQueryStrings" minOccurs="0"/>
            <xs:element name="post_body" minOccurs="0" type="xPostBody"/>
        </xs:sequence>
        <xs:attribute name="method" use="required" type="httpMethodType"/>
        <xs:attribute name="target" use="required" type="xs:string"/>
    </xs:complexType>
    <xs:simpleType name="httpMethodType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="get"/>
            <xs:enumeration value="post"/>
            <xs:enumeration value="delete"/>
            <xs:enumeration value="put"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="xResponse">
        <xs:choice minOccurs="0">
            <xs:element name="json_parser" type="xJsonParser"/>
        </xs:choice>
        <xs:attribute name="model" use="required" type="nameType"/>
    </xs:complexType>
    <xs:complexType name="xJsonParser">
        <xs:choice>
            <xs:element name="json_checker"/>
            <xs:element name="json_value"/>
            <xs:element name="json_object_array"/>
            <xs:element name="json_object"/>
        </xs:choice>
        <xs:attribute name="model" type="nameType"/>
    </xs:complexType>
    <xs:complexType name="xInputs">
        <xs:choice>
            <xs:element name="string" type="xType"/>
            <xs:element name="int" type="xType"/>
            <xs:element name="decimal" type="xType"/>
            <xs:element name="boolean" type="xType"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="xQueryStrings">
        <xs:choice>
            <xs:element name="query" type="xQuery"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="xQuery">
        <xs:attribute name="name" use="required" type="nameType"/>
        <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="xPostBody">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="attribute" type="xVarious"/>
        </xs:choice>
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="xVarious">
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>
</xs:schema>

=== macomfan/cei/exchanges/huobipro/models/Candlestick.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="https://github.com/macomfan/cei https://github.com/macomfan/cei/ceisdk.xsd"
     xmlns="https://github.com/macomfan/cei"
     name="huobipro">
    <models>
        <model name="Candlestick">
            <string name="status"/>
            <object_array name="data" refer="CandlestickData"/>
        </model>

        <model name="CandlestickData">
            <int name="id"/>
            <decimal name="amount"/>
            <int name="count"/>
            <decimal name="open"/>
            <decimal name="close"/>
            <decimal name="low"/>
            <decimal name="high"/>
            <decimal name="vol"/>
        </model>
    </models>
</sdk>

=== macomfan/cei/exchanges/binance/restful/MarketClient/getDepth.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="https://github.com/macomfan/cei https://github.com/macomfan/cei/ceisdk.xsd"
	 xmlns="https://github.com/macomfan/cei"
	 name="binance">
	<restful name="MarketClient">
		<interface name="getDepth">
			<inputs>
				<string name="symbol"/>
				<int name="limit"/>
			</inputs>
			<request method="get" target="/api/v3/depth">
				<query_strings>
					<query key="symbol" value="{symbol}"/>
					<query key="limit" value="{limit}"/>
				</query_strings>
			</request>
			<response model="Depth">
				<json_parser>
					<json_value copy="lastUpdateId"/>
					<json_object_array copy="bids" model="DepthEntity">
						<json_value key="\[0]" value="{price}"/>
						<json_value key="\[1]" value="{qty}"/>
					</json_object_array>
					<json_object_array copy="asks" model="DepthEntity">
						<json_value key="\[0]" value="{price}"/>
						<json_value key="\[1]" value="{qty}"/>
					</json_object_array>
				</json_parser>
			</response>
		</interface>
	</restful>
</sdk>

=== macomfan/cei/exchanges/binance/restful/MarketClient/getExchangeInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="https://github.com/macomfan/cei https://github.com/macomfan/cei/ceisdk.xsd"
	 xmlns="https://github.com/macomfan/cei"
	 name="binance">
	<clients>
		<restful name="MarketClient">
			<interfaces>
				<interface name="getExchangeInfo">
					<request method="get" target="/api/v3/exchangeInfo"/>
					<response model="ExchangeInfo">
						<json_parser>
							<json_value copy="timezone"/>
							<json_value copy="serverTime"/>
							<json_object_array copy="rateLimits" model="RateLimits">
								<json_value copy="rateLimitType"/>
								<json_value copy="interval"/>
								<json_value copy="intervalNum"/>
								<json_value copy="limit"/>
							</json_object_array>
							<json_object_array copy="symbols" model="Symbol">
								<json_value copy="symbol"/>
								<json_value copy="status"/>
								<json_value copy="baseAsset"/>
								<json_value copy="baseAssetPrecision"/>
								<json_value copy="quoteAsset"/>
								<json_value copy="quotePrecision"/>
								<json_value copy="orderTypes"/>
								<json_value copy="icebergAllowed"/>
								<json_value copy="ocoAllowed"/>
							</json_object_array>
						</json_parser>
					</response>
				</interface>
			</interfaces>

		</restful>
	</clients>

</sdk>

=== macomfan/cei/exchanges/binance/restful/MarketClient/getAggregateTrades.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="https://github.com/macomfan/cei https://github.com/macomfan/cei/ceisdk.xsd"
     xmlns="https://github.com/macomfan/cei"
     name="binance">
    <clients>
        <restful name="MarketClient">
            <interfaces>
                <interface name="getAggregateTrades">
                    <inputs>
                        <string name="symbol"/>
                        <int name="fromId"/>
                        <int name="startTime"/>
                        <int name="endTime"/>
                        <int name="limit"/>
                    </inputs>
                    <request method="get" target="/api/v3/aggTrades">
                        <query_strings>
                            <query key="symbol" value="{symbol}"/>
                            <query key="fromId" value="{fromId}"/>
                            <query key="startTime" value="{startTime}"/>
                            <query key="startTime" value="{endTime}"/>
                            <query key="limit" value="{limit}"/>
                        </query_strings>
                    </request>
                    <response>
                        <json_parser model="AggregateTradeList">
                            <json_object_array value="{data}" model="AggregateTrade">
                                <json_value key="a" value="{id}"/>
                                <json_value key="p" value="{price}"/>
                                <json_value key="q" value="{qty}"/>
                                <json_value key="f" value="{firstTradeId}"/>
                                <json_value key="l" value="{lastTradeId}"/>
                                <json_value key="T" value="{timestamp}"/>
                                <json_value key="m" value="{isBuyerMaker}"/>
                                <json_value key="M" value="{isBestMatch}"/>
                            </json_object_array>
                        </json_parser>
                    </response>
                </interface>
            </interfaces>
        </restful>
    </clients>

</sdk>

=== macomfan/cei/exchanges/binance/models/Trade.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="https://github.com/macomfan/cei https://github.com/macomfan/cei/ceisdk.xsd"
     xmlns="https://github.com/macomfan/cei"
     name="binance">
	<model name="Trade">
		<int name="id"/>
		<decimal name="price"/>
		<decimal name="qty"/>
		<decimal name="quoteQty"/>
		<int name="time"/>
		<boolean name="isBuyerMaker"/>
		<boolean name="isBestMatch"/>
	</model>
</sdk>

=== macomfan/cei/exchanges/binance/restful/MarketClient/getCandlestickData.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="https://github.com/macomfan/cei https://github.com/macomfan/cei/ceisdk.xsd"
	 xmlns="https://github.com/macomfan/cei"
	 name="binance">
	<restful name="MarketClient">
		<interface name="getCandlestickData">
			<inputs>
				<string name="symbol"/>
				<string name="interval"/>
				<int name="startTime"/>
				<int name="endTime"/>
				<int name="limit"/>
			</inputs>
			<request method="get" target="/api/v3/klines">
				<query_strings>
					<query key="symbol" value="{symbol}"/>
					<query key="interval" value="{interval}"/>
					<query key="startTime" value="{startTime}"/>
					<query key="endTime" value="{endTime}"/>
					<query key="limit" value="{limit}"/>
				</query_strings>
			</request>
			<response model="CandlestickDataList">
				<json_parser>
					<json_object_array value="{data}" model="CandlestickData">
						<json_value key="\[0]" value="{price}"/>
						<json_value key="\[1]" value="{amount}"/>
					</json_object_array>
				</json_parser>
			</response>
		</interface>
	</restful>
</sdk>

=== macomfan/cei/exchanges/binance/restful/MarketClient/getHistoricalTrades.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="https://github.com/macomfan/cei https://github.com/macomfan/cei/ceisdk.xsd"
     xmlns="https://github.com/macomfan/cei"
     name="binance">
    <clients>
        <restful name="MarketClient">
            <interfaces>
                <interface name="historicalTrades">
                    <inputs>
                        <string name="symbol"/>
                        <int name="limit"/>
                        <int name="fromId"/>
                    </inputs>
                    <request method="get" target="/api/v3/historicalTrades" signature="TBD">
                        <query_strings>
                            <query key="symbol" value="{symbol}"/>
                            <query key="limit" value="{limit}"/>
                            <query key="fromId" value="{fromId}"/>
                        </query_strings>
                    </request>
                    <response>
                        <json_parser model="TradeList">
                            <json_object_for_each value="{data}" model="Trade">
                                <json_value copy="id"/>
                                <json_value copy="price"/>
                                <json_value copy="qty"/>
                                <json_value copy="quoteQty"/>
                                <json_value copy="time"/>
                                <json_value copy="isBuyerMaker"/>
                                <json_value copy="isBestMatch"/>
                            </json_object_for_each>
                        </json_parser>
                    </response>
                </interface>
            </interfaces>

        </restful>
    </clients>

</sdk>

=== macomfan/cei/exchanges/binance/models/CandlestickData.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="https://github.com/macomfan/cei https://github.com/macomfan/cei/ceisdk.xsd"
     xmlns="https://github.com/macomfan/cei"
     name="binance">
	<models>
		<model name="CandlestickData">
			<int name="openTime"/>
			<decimal name="open"/>
			<decimal name="high"/>
			<decimal name="low"/>
			<decimal name="close"/>
			<decimal name="volume"/>
			<int name="closeTime"/>
			<decimal name="quoteAssetVolume"/>
			<int name="numberOfTrades"/>
			<decimal name="takerBuyBaseAssetVolume"/>
			<decimal name="takerBuyQuoteAssetVolume"/>
		</model>
	</models>
</sdk>
