=== macomfan/cei/schema/ceisdk-0.0.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://github.com/macomfan/cei"
           xmlns="https://github.com/macomfan/cei"
           elementFormDefault="qualified"
           version="0.0.1">
    <xs:element name="sdk" type="xSDK"/>

    <xs:complexType name="xSDK">
        <xs:all>
            <xs:element name="definition" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="document"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="models" minOccurs="0">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="model" type="xModel"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="procedures" minOccurs="0">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="function" type="xFunction" maxOccurs="unbounded"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="clients" minOccurs="0">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="restful" type="xRestful"/>
                        <xs:element name="websocket" type="xWebSocket"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>


    <xs:complexType name="xSDKDef">
        <xs:attribute name="document"/>
    </xs:complexType>

    <xs:complexType name="xModel">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="string" type="xType"/>
            <xs:element name="int" type="xType"/>
            <xs:element name="decimal" type="xType"/>
            <xs:element name="boolean" type="xType"/>
            <xs:element name="object" type="xObject"/>
            <xs:element name="object_array" type="xObjectArray"/>
            <xs:element name="string_array" type="xType"/>
            <xs:element name="int_array" type="xType"/>
            <xs:element name="decimal_array" type="xType"/>
            <xs:element name="boolean_array" type="xType"/>
        </xs:choice>
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>

    <xs:complexType name="xRestful">
        <xs:all>
            <xs:element name="connection" type="xConnection" minOccurs="0"/>
            <xs:element name="interfaces" minOccurs="0">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="interface">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="inputs" minOccurs="0" type="xInputs"/>
                                    <xs:element name="request" type="xRequest"/>
                                    <xs:element name="response" type="xResponse"/>
                                </xs:sequence>
                                <xs:attribute name="name" use="required" type="nameType"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>

    <xs:complexType name="xWebSocket">
        <xs:all>
            <xs:element name="connection" type="xWSConnection" minOccurs="0"/>
            <xs:element name="actions" minOccurs="0">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="action">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="trigger" type="xTrigger"/>
                                    <xs:element name="send" type="xSend"/>
                                </xs:sequence>
                                <xs:attribute name="name" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="interfaces" minOccurs="0">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="interface">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="inputs" minOccurs="0" type="xInputs"/>
                                    <xs:element name="send" minOccurs="0" type="xSend"/>
                                    <xs:element name="callback" type="xCallback" maxOccurs="unbounded"/>
                                </xs:sequence>
                                <xs:attribute name="name" use="required" type="nameType"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>

    <xs:complexType name="xType">
        <xs:attribute name="name" use="required" type="nameType"/>
    </xs:complexType>
    <xs:complexType name="xObject">
        <xs:attribute name="name" use="required" type="nameType"/>
        <xs:attribute name="model" use="required" type="nameType"/>
    </xs:complexType>
    <xs:complexType name="xObjectArray">
        <xs:attribute name="name" use="required" type="nameType"/>
        <xs:attribute name="model" use="required" type="nameType"/>
    </xs:complexType>

    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z]+[A-Za-z0-9_]*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="variableType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\{[A-Za-z]+[A-Za-z0-9_]*\}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="xRequest">
        <xs:sequence>
            <xs:element name="pre_processor" type="xProcedure" minOccurs="0"/>
            <xs:element name="query_strings" type="xQueryStrings" minOccurs="0"/>
            <xs:element name="post_body" minOccurs="0" type="xPostBody"/>
            <xs:element name="authentication" minOccurs="0" type="xAuthentication"/>
        </xs:sequence>
        <xs:attribute name="method" use="required" type="httpMethodType"/>
        <xs:attribute name="target" use="required" type="xs:string"/>
    </xs:complexType>
    <xs:simpleType name="httpMethodType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="get"/>
            <xs:enumeration value="post"/>
            <xs:enumeration value="delete"/>
            <xs:enumeration value="put"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="xResponse">
        <xs:complexContent>
            <xs:extension base="xProcedure">
                <xs:attribute name="name" type="nameType"/>
                <xs:attribute name="result" type="variableType"/>
                <xs:attribute name="type" type="ResponseType"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="xInputs">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="string" type="xType"/>
            <xs:element name="int" type="xType"/>
            <xs:element name="decimal" type="xType"/>
            <xs:element name="boolean" type="xType"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="xQueryStrings">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="query" type="xQuery"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="xQuery">
        <xs:attribute name="key" use="required" type="nameType"/>
        <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="xPostBody">
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>


    <!--======== For JSON Start =======-->
    <xs:complexType name="xJsonType">
        <xs:attribute name="key" type="xs:string"/>
        <xs:attribute name="copy" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="xJsonWithSubItems">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="json_value" type="xJsonType"/>
            <xs:element name="json_string" type="xJsonType"/>
            <xs:element name="json_boolean" type="xJsonType"/>
            <xs:element name="json_decimal" type="xJsonType"/>
            <xs:element name="json_object_for_each" type="xJsonTypeWithModel"/>
            <xs:element name="json_object" type="xJsonTypeWithModel"/>
            <xs:element name="json_string_array" type="xJsonType"/>
            <xs:element name="json_int_array" type="xJsonType"/>
            <xs:element name="json_boolean_array" type="xJsonType"/>
            <xs:element name="json_decimal_array" type="xJsonType"/>
            <xs:element name="json_checker_equal" type="xJsonCheckerItem"/>
            <xs:element name="json_checker_not_equal" type="xJsonCheckerItem"/>
        </xs:choice>
    </xs:complexType>


    <xs:complexType name="xJsonParser">
        <xs:complexContent>
            <xs:restriction base="xJsonWithSubItems">
                <xs:choice minOccurs="0">
                    <xs:element name="json_checker" type="xJsonWithSubItems"/>
                </xs:choice>
                <xs:attribute name="model" type="nameType" use="required"/>
                <xs:attribute name="name" type="nameType"/>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="xJsonTypeWithModel">
        <xs:complexContent>
            <xs:extension base="xJsonWithSubItems">
                <xs:attribute name="key" type="xs:string"/>
                <xs:attribute name="copy" type="xs:string"/>
                <xs:attribute name="value" type="xs:string"/>
                <xs:attribute name="model" type="nameType"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="xJsonBuilder">
        <xs:complexContent>
            <xs:extension base="xJsonWithSubItems">
                <xs:attribute name="name" type="nameType"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="xJsonCheckerItem">
        <xs:attribute name="key"/>
        <xs:attribute name="value"/>
    </xs:complexType>

    <xs:complexType name="xJsonBuilderItem">
        <xs:attribute name="key" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
        <xs:attribute name="copy" type="xs:string"/>
    </xs:complexType>

    <!--======== For JSON End =======-->

    <!--======== For Function Start =========-->
    <xs:complexType name="xProcedure">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="json_parser" type="xJsonParser"/>
            <xs:element name="json_builder" type="xJsonBuilder"/>
            <xs:element name="get_now" type="xGetNow"/>
            <xs:element name="string_builder" type="xStringBuilder"/>
            <xs:element name="hmacsha256" type="xHmacsha256"/>
            <xs:element name="base64" type="xBase64"/>
            <xs:element name="get_now" type="xGetNow"/>
            <xs:element name="url_escape" type="xURLEscape"/>
            <xs:element name="string_builder" type="xStringBuilder"/>
            <xs:element name="add_query_string" type="xAddQueryString"/>
            <xs:element name="combine_query_string" type="xCombineQueryString"/>
            <xs:element name="get_request_info" type="xGetRequestInfo"/>
            <xs:element name="invoke" type="xInvoke"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="xExtendInput">
        <xs:complexContent>
            <xs:extension base="xInputs">
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="restful_request" type="xType"/>
                    <xs:element name="restful_options" type="xType"/>
                    <xs:element name="restful_response" type="xType"/>
                    <xs:element name="websocket_message" type="xType"/>
                    <xs:element name="websocket_request" type="xType"/>
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="xFunction">
        <xs:sequence>
            <xs:element name="inputs" minOccurs="0" type="xExtendInput"/>
            <xs:element name="implementation" type="xProcedure"/>
        </xs:sequence>
        <xs:attribute name="name" type="nameType" use="required"/>
        <xs:attribute name="return" type="variableType"/>
    </xs:complexType>
    <!--======== For Function End   =========-->

    <!-- Data processor -->
    <xs:complexType name="xGetNow">
        <xs:attribute name="name" type="nameType"/>
        <xs:attribute name="format" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="xAddQueryString">
        <xs:attribute name="input" type="variableType" use="required"/>
        <xs:attribute name="key" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="xCombineQueryString">
        <xs:attribute name="input" type="variableType" use="required"/>
        <xs:attribute name="name" type="nameType"/>
        <xs:attribute name="sort"/>
        <xs:attribute name="separator"/>
    </xs:complexType>
    <xs:complexType name="xGetRequestInfo">
        <xs:attribute name="input" type="variableType" use="required"/>
        <xs:attribute name="name" type="nameType"/>
        <xs:attribute name="info"/>
        <xs:attribute name="convert"/>
    </xs:complexType>
    <xs:complexType name="xHmacsha256">
        <xs:attribute name="name" type="nameType"/>
        <xs:attribute name="input"/>
        <xs:attribute name="key"/>
    </xs:complexType>
    <xs:complexType name="xBase64">
        <xs:attribute name="name" type="nameType"/>
        <xs:attribute name="input"/>
    </xs:complexType>

    <xs:complexType name="xConnection">
        <xs:attribute name="url" type="xs:string" use="required"/>
        <xs:attribute name="timeout_s" type="xs:integer"/>
    </xs:complexType>


    <xs:complexType name="xCallback">
        <xs:sequence>
            <xs:element name="trigger" type="xTrigger"/>
            <xs:element name="response" type="xResponse"/>
        </xs:sequence>
        <xs:attribute name="name" use="required" type="nameType"/>
        <xs:attribute name="persistent" use="required" type="xs:boolean"/>
    </xs:complexType>
    <xs:simpleType name="WebSocketCallbackType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="disposable"/>
            <xs:enumeration value="persistent"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="xTrigger">
        <xs:choice>
            <xs:element name="json_checker" type="xJsonWithSubItems"/>
        </xs:choice>
        <xs:attribute name="timeout_s" type="xs:integer"/>
        <xs:attribute name="interval_s" type="xs:integer"/>
    </xs:complexType>
    <xs:complexType name="xSend">
        <xs:complexContent>
            <xs:extension base="xProcedure">
                <xs:attribute name="value" type="xs:string" use="required"/>
                <xs:attribute name="type" type="WebSocketSendType"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="WebSocketSendType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="string"/>
            <xs:enumeration value="binary"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ResponseType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="string"/>
            <xs:enumeration value="binary"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="xStringBuilder">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="add_string_item" type="xAddStringItem"/>
            <xs:element name="combine_string_items" type="xCombineStringItems"/>
        </xs:choice>
        <xs:attribute name="name" type="nameType"/>
    </xs:complexType>
    <xs:complexType name="xAddStringItem">
        <xs:attribute name="input"/>
    </xs:complexType>
    <xs:complexType name="xCombineStringItems">
        <xs:attribute name="separator"/>
    </xs:complexType>
    <xs:complexType name="xWSConnection">
        <xs:sequence>
            <xs:element name="inputs" type="xInputs" minOccurs="0"/>
            <xs:element name="url" type="xWSUrl"/>
            <xs:element name="on_connect" minOccurs="0" type="xWSOnConnect"/>
        </xs:sequence>
        <xs:attribute name="timeout_s" type="xs:integer"/>
    </xs:complexType>
    <xs:complexType name="xWSUrl">
        <xs:choice minOccurs="0">
            <xs:element name="attribute" type="xProcedure"/>
        </xs:choice>
        <xs:attribute name="target"/>
    </xs:complexType>
    <xs:complexType name="xWSOnConnect">
        <xs:choice minOccurs="0">
            <xs:element name="send" type="xSend"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="xURLEscape">
        <xs:attribute name="name" type="nameType"/>
        <xs:attribute name="input" type="variableType"/>
    </xs:complexType>

    <xs:complexType name="xAuthentication">
        <xs:attribute name="name" type="nameType" use="required"/>
        <xs:attribute name="arguments" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="xInvoke">
        <xs:attribute name="function" type="nameType" use="required"/>
        <xs:attribute name="return" type="variableType"/>
        <xs:attribute name="arguments" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== macomfan/cei/exchanges/binance/restful/MarketClient.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="https://github.com/macomfan/cei https://macomfan.github.io/cei/schema/ceisdk-0.0.1.xsd"
     xmlns="https://github.com/macomfan/cei"
     name="binance">
    <clients>
        <restful name="MarketClient">
			<connection url="https://api.binance.com"/>
            <interfaces>
                <interface name="getTimestamp">
                    <request method="get" target="/api/v3/time"/>
                    <response>
                        <json_parser model="Timestamp">
                            <json_value copy="serverTime"/>
                        </json_parser>
                    </response>
                </interface>
                <interface name="getAggregateTrades">
                    <inputs>
                        <string name="symbol"/>
                        <int name="fromId"/>
                        <int name="startTime"/>
                        <int name="endTime"/>
                        <int name="limit"/>
                    </inputs>
                    <request method="get" target="/api/v3/aggTrades">
                        <query_strings>
                            <query key="symbol" value="{symbol}"/>
                            <query key="fromId" value="{fromId}"/>
                            <query key="startTime" value="{startTime}"/>
                            <query key="startTime" value="{endTime}"/>
                            <query key="limit" value="{limit}"/>
                        </query_strings>
                    </request>
                    <response>
                        <json_parser model="AggregateTradeList">
                            <json_object_for_each value="{data}" model="AggregateTrade">
                                <json_value key="a" value="{id}"/>
                                <json_value key="p" value="{price}"/>
                                <json_value key="q" value="{qty}"/>
                                <json_value key="f" value="{firstTradeId}"/>
                                <json_value key="l" value="{lastTradeId}"/>
                                <json_value key="T" value="{timestamp}"/>
                                <json_value key="m" value="{isBuyerMaker}"/>
                                <json_value key="M" value="{isBestMatch}"/>
                            </json_object_for_each>
                        </json_parser>
                    </response>
                </interface>
                <interface name="getTrade">
                    <inputs>
                        <string name="symbol"/>
                        <int name="limit"/>
                    </inputs>
                    <request method="get" target="/api/v3/trades">
                        <query_strings>
                            <query key="symbol" value="{symbol}"/>
                            <query key="limit" value="{limit}"/>
                        </query_strings>
                    </request>
                    <response>
                        <json_parser model="TradeList">
                            <json_object_for_each value="{data}" model="Trade">
                                <json_value copy="id"/>
                                <json_value copy="price"/>
                                <json_value copy="qty"/>
                                <json_value copy="quoteQty"/>
                                <json_value copy="time"/>
                                <json_value copy="isBuyerMaker"/>
                                <json_value copy="isBestMatch"/>
                            </json_object_for_each>
                        </json_parser>
                    </response>
                </interface>
                <interface name="historicalTrades">
                    <inputs>
                        <string name="symbol"/>
                        <int name="limit"/>
                        <int name="fromId"/>
                    </inputs>
                    <request method="get" target="/api/v3/historicalTrades" signature="TBD">
                        <query_strings>
                            <query key="symbol" value="{symbol}"/>
                            <query key="limit" value="{limit}"/>
                            <query key="fromId" value="{fromId}"/>
                        </query_strings>
                    </request>
                    <response>
                        <json_parser model="TradeList">
                            <json_object_for_each value="{data}" model="Trade">
                                <json_value copy="id"/>
                                <json_value copy="price"/>
                                <json_value copy="qty"/>
                                <json_value copy="quoteQty"/>
                                <json_value copy="time"/>
                                <json_value copy="isBuyerMaker"/>
                                <json_value copy="isBestMatch"/>
                            </json_object_for_each>
                        </json_parser>
                    </response>
                </interface>
                <interface name="getExchangeInfo">
                    <request method="get" target="/api/v3/exchangeInfo"/>
                    <response>
                        <json_parser model="ExchangeInfo">
                            <json_value copy="timezone"/>
                            <json_value copy="serverTime"/>
                            <json_object_for_each copy="rateLimits" model="RateLimits">
                                <json_value copy="rateLimitType"/>
                                <json_value copy="interval"/>
                                <json_value copy="intervalNum"/>
                                <json_value copy="limit"/>
                            </json_object_for_each>
                            <json_object_for_each copy="symbols" model="Symbol">
                                <json_value copy="symbol"/>
                                <json_value copy="status"/>
                                <json_value copy="baseAsset"/>
                                <json_value copy="baseAssetPrecision"/>
                                <json_value copy="quoteAsset"/>
                                <json_value copy="quotePrecision"/>
                                <json_value copy="orderTypes"/>
                                <json_value copy="icebergAllowed"/>
                                <json_value copy="ocoAllowed"/>
                            </json_object_for_each>
                        </json_parser>
                    </response>
                </interface>
                <interface name="getDepth">
                    <inputs>
                        <string name="symbol"/>
                        <int name="limit"/>
                    </inputs>
                    <request method="get" target="/api/v3/depth">
                        <query_strings>
                            <query key="symbol" value="{symbol}"/>
                            <query key="limit" value="{limit}"/>
                        </query_strings>
                    </request>
                    <response>
                        <json_parser model="Depth">
                            <json_value copy="lastUpdateId"/>
                            <json_object_for_each copy="bids" model="DepthEntity">
                                <json_value key="[0]" value="{price}"/>
                                <json_value key="[1]" value="{qty}"/>
                            </json_object_for_each>
                            <json_object_for_each copy="asks" model="DepthEntity">
                                <json_value key="[0]" value="{price}"/>
                                <json_value key="[1]" value="{qty}"/>
                            </json_object_for_each>
                        </json_parser>
                    </response>
                </interface>
                <interface name="getCandlestickData">
                    <inputs>
                        <string name="symbol"/>
                        <string name="interval"/>
                        <int name="startTime"/>
                        <int name="endTime"/>
                        <int name="limit"/>
                    </inputs>
                    <request method="get" target="/api/v3/klines">
                        <query_strings>
                            <query key="symbol" value="{symbol}"/>
                            <query key="interval" value="{interval}"/>
                            <query key="startTime" value="{startTime}"/>
                            <query key="endTime" value="{endTime}"/>
                            <query key="limit" value="{limit}"/>
                        </query_strings>
                    </request>
                    <response>
                        <json_parser model="CandlestickDataList">
                            <json_object_for_each value="{data}" model="CandlestickData">
                                <json_value key="\[0]" value="{open}"/>
                                <json_value key="\[1]" value="{high}"/>
                            </json_object_for_each>
                        </json_parser>
                    </response>
                </interface>
            </interfaces>
        </restful>
    </clients>

</sdk>

=== macomfan/cei/exchanges/huobipro/models/Trade.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="https://github.com/macomfan/cei https://macomfan.github.io/cei/schema/ceisdk-0.0.1.xsd"
     xmlns="https://github.com/macomfan/cei"
     name="huobipro">
    <models>
        <model name="Trade">
            <int name="id"/>
            <int name="tradeID"/>
            <decimal name="price"/>
            <decimal name="amount"/>
            <string name="direction"/>
            <int name="ts"/>
        </model>
    </models>

</sdk>

=== macomfan/cei/exchanges/binance/models/AggregateTrade.xml
<?xml version="1.0" encoding="UTF-8"?>
<sdk xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="https://github.com/macomfan/cei https://macomfan.github.io/cei/schema/ceisdk-0.0.1.xsd"
     xmlns="https://github.com/macomfan/cei"
     name="binance">
    <models>
        <model name="AggregateTrade">
            <int name="id"/>
            <decimal name="price"/>
            <decimal name="qty"/>
            <int name="timestamp"/>
            <int name="firstTradeId"/>
            <int name="lastTradeId"/>
            <boolean name="isBuyerMaker"/>
            <boolean name="isBestMatch"/>
        </model>
    </models>
</sdk>
